version: '3'

vars:
  test_commands: |
    test/sleep

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - all

  all:
    desc: 'Build and test everything'
    deps:
      - build
      - test

  build:
    desc: 'Build all components'
    deps:
      - build-commands

  build-commands:
    desc: 'Build all commands'
    deps:
      - build-memsparkline
      - build-test-commands

  build-package:
    desc: 'Build a single Go package'
    internal: true
    dir: '{{.package}}'
    cmds:
      - go build -trimpath

  build-memsparkline:
    desc: 'Build the memsparkline command'
    cmds:
      - task: build-package
        vars:
          package: .
    sources:
      - main.go
    generates:
      - memsparkline{{exeExt}}

  build-test-commands:
    desc: 'Build all test commands'
    cmds:
      - task: build-package
        vars:
          package: '{{.test_command}}'
        for:
          var: test_commands
          as: test_command
    sources:
      - test/**/*.go
    generates:
      - test/sleep/sleep{{exeExt}}

  clean:
    desc: 'Clean up binaries'
    cmds:
      - rm -f memsparkline{{exeExt}}
      - cmd: rm -f {{.test_command | shellQuote}}{{.test_command | base | shellQuote}}{{exeExt}}
        for:
          var: test_commands
          as: test_command

  release:
    desc: 'Prepare a release'
    deps:
      - build-commands
    cmds:
      - VERSION=$(./memsparkline{{exeExt}} --version) go run script/release.go

  test:
    desc: 'Run tests'
    deps:
      - build-commands
    cmds:
      - go test
