version: '3'

vars:
  TEST_HELPERS: |
    test/sleep

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - all

  all:
    desc: 'Build and test everything'
    deps:
      - build
      - test

  build:
    desc: 'Build all components'
    deps:
      - build:memsparkline
      - build:helpers

  build:package:
    desc: 'Build a single Go package'
    internal: true
    dir: '{{.PACKAGE}}'
    cmds:
      - 'go build -trimpath # {{.PACKAGE}}'

  build:memsparkline:
    desc: 'Build the memsparkline binary'
    run: once
    cmds:
      - task: build:package
        vars:
          PACKAGE: .
    sources:
      - main.go
    generates:
      - memsparkline{{exeExt}}

  build:helpers:
    desc: 'Build all test helpers'
    run: once
    cmds:
      - task: build:package
        vars:
          PACKAGE: '{{.HELPER}}'
        for:
          var: TEST_HELPERS
          as: HELPER
    sources:
      - test/**/*.go
    status:
      - '{{range $i, $path := .TEST_HELPERS | trim | splitLines}}{{if $i}} && {{end}}test -f {{$path | shellQuote}}/{{$path | base | shellQuote}}{{exeExt}}{{end}}'

  check:
    desc: 'Build, format, lint, and test everything'
    deps:
      - build
      - format
      - lint
      - test

  clean:
    desc: 'Clean up binaries'
    cmds:
      - rm -f memsparkline{{exeExt}}
      - cmd: rm -f {{.HELPER | shellQuote}}/{{.HELPER | base | shellQuote}}{{exeExt}}
        for:
          var: TEST_HELPERS
          as: HELPER

  format:
    desc: 'Format source code'
    cmds:
      - golangci-lint fmt

  lint:
    desc: 'Run linters'
    cmds:
      - golangci-lint run

  release:
    desc: 'Prepare a release'
    deps:
      - build
    cmds:
      - VERSION=$(./memsparkline{{exeExt}} --version) go run script/release.go

  test:
    desc: 'Run tests'
    deps:
      - build
    cmds:
      - go test
